/*
  JWildfire - an image and animation processor written in Java 
  Copyright (C) 1995-2015 Andreas Maschke

  This is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser 
  General Public License as published by the Free Software Foundation; either version 2.1 of the 
  License, or (at your option) any later version.
 
  This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without 
  even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License along with this software; 
  if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  02110-1301 USA, or see the FSF site: http://www.fsf.org.
*/
package org.jwildfire.create.tina.integration.chaotica;

import java.util.ArrayList;
import java.util.List;

import org.jwildfire.base.Prefs;
import org.jwildfire.create.tina.base.Flame;
import org.jwildfire.create.tina.randomflame.BlackAndWhiteRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.Brokat3DRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.BrokatRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.Bubbles3DRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.BubblesRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.CrossRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.DualityRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.DuckiesRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.ExperimentalBubbles3DRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.ExperimentalGnarlRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.ExperimentalSimpleRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.FilledFlowers3DRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.Flowers3DRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.GalaxiesRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.GhostsRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.GnarlRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.JulianDiscRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.JuliansRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.LayerzRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.LinearRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.MandelbrotRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.RandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.RandomFlameGeneratorState;
import org.jwildfire.create.tina.randomflame.RaysRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.SierpinskyRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.SimpleRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.SimpleTilingRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.Spherical3DRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.SphericalRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.SplitsRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.SynthRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.TentacleRandomFlameGenerator;
import org.jwildfire.create.tina.randomflame.XenomorphRandomFlameGenerator;
import org.jwildfire.create.tina.randomgradient.RandomGradientGenerator;

// Meta-Random-Flame-Generator which tries to transform random flames (generated by other random-flame-generators) that they can be rendered using the  Chaotica
public class ChaoticaBridgeRandomFlameGenerator extends RandomFlameGenerator {
  private static List<RandomFlameGenerator> generators;
  private ChaoticaExporter chaotifier = new ChaoticaExporter();

  static {
    generators = new ArrayList<RandomFlameGenerator>();
    generators.add(new BrokatRandomFlameGenerator());
    generators.add(new Brokat3DRandomFlameGenerator());
    generators.add(new BubblesRandomFlameGenerator());
    generators.add(new DualityRandomFlameGenerator());
    generators.add(new Bubbles3DRandomFlameGenerator());
    generators.add(new CrossRandomFlameGenerator());
    generators.add(new DualityRandomFlameGenerator());
    generators.add(new GalaxiesRandomFlameGenerator());
    generators.add(new DuckiesRandomFlameGenerator());
    generators.add(new ExperimentalBubbles3DRandomFlameGenerator());
    generators.add(new ExperimentalGnarlRandomFlameGenerator());
    generators.add(new ExperimentalSimpleRandomFlameGenerator());
    generators.add(new FilledFlowers3DRandomFlameGenerator());
    generators.add(new Flowers3DRandomFlameGenerator());
    generators.add(new GnarlRandomFlameGenerator());
    generators.add(new JuliansRandomFlameGenerator());
    generators.add(new DualityRandomFlameGenerator());
    generators.add(new GalaxiesRandomFlameGenerator());
    generators.add(new MandelbrotRandomFlameGenerator());
    generators.add(new JulianDiscRandomFlameGenerator());
    generators.add(new LayerzRandomFlameGenerator());
    generators.add(new LinearRandomFlameGenerator());
    generators.add(new RaysRandomFlameGenerator());
    generators.add(new SimpleRandomFlameGenerator());
    generators.add(new SimpleTilingRandomFlameGenerator());
    generators.add(new SierpinskyRandomFlameGenerator());
    generators.add(new DualityRandomFlameGenerator());
    generators.add(new GalaxiesRandomFlameGenerator());
    generators.add(new SphericalRandomFlameGenerator());
    generators.add(new Spherical3DRandomFlameGenerator());
    generators.add(new GhostsRandomFlameGenerator());
    generators.add(new SplitsRandomFlameGenerator());
    generators.add(new SynthRandomFlameGenerator());
    generators.add(new TentacleRandomFlameGenerator());
    generators.add(new DualityRandomFlameGenerator());
    generators.add(new XenomorphRandomFlameGenerator());
    generators.add(new BlackAndWhiteRandomFlameGenerator());
  }

  private static final String RANDGEN = "RANDGEN";

  @Override
  public RandomFlameGeneratorState initState(Prefs pPrefs, RandomGradientGenerator pRandomGradientGenerator) {
    RandomFlameGeneratorState state = super.initState(pPrefs, pRandomGradientGenerator);
    RandomFlameGenerator generator = generators.get((int) (Math.random() * generators.size()));
    state.getParams().put(RANDGEN, generator);
    return state;
  }

  @Override
  public Flame prepareFlame(RandomFlameGeneratorState pState) {
    RandomFlameGenerator generator = createRandGen(pState);
    RandomFlameGeneratorState subState = generator.initState(pState.getPrefs(), pState.getGradientGenerator());
    Flame flame = generator.prepareFlame(subState);
    flame.setName(generator.getName() + " - " + flame.hashCode());
    return flame;
  }

  private RandomFlameGenerator createRandGen(RandomFlameGeneratorState pState) {
    RandomFlameGenerator generator = (RandomFlameGenerator) pState.getParams().get(RANDGEN);
    return generator;
  }

  @Override
  public String getName() {
    return "Chaotica Bridge";
  }

  @Override
  public boolean isUseFilter(RandomFlameGeneratorState pState) {
    return false;
  }

  @Override
  protected Flame postProcessFlame(RandomFlameGeneratorState pState, Flame pFlame) {
    chaotifier.doExport(pFlame);
    return pFlame;
  }

  @Override
  public boolean supportsSymmetry() {
    return false;
  }

}
